# Generated by Django 2.1.1 on 2018-10-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='account',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bsb',
            field=models.CharField(max_length=7),
        ),
    ]
