# Generated by Django 2.1.2 on 2018-10-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20181027_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='crust',
            field=models.CharField(default='regular', max_length=50),
        ),
    ]
