# Generated by Django 2.1.2 on 2018-11-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_order_crust'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(default='', max_length=50),
        ),
    ]
